### PR TITLE
Fixed incorrect transparency when quickly switching workspaces

### PR DESCRIPTION
**Pull request by stuarthayhurst**
When quickly switching between workspaces (VERY quickly, using the keyboard), the transparency may fall out of sync.
If the first workspace has windows on the top edge and the second is empty, quickly switching would lead to a transparent top bar, with windows attached to it.

After troubleshooting, it turns out the shell is running behind, and reports information about the windows (or lack of windows) on the second workspace, when we're actually back on the first workspace.
As a workaround, a 100ms delay was added to fix this. It's completely unnoticeable regularly (because the switching animation hides it), but it's enough time for the shell to catch up and work around the issue.

The signal disconnect in `disable()` will probably never be required in practice, but it's required to pass the review to be uploaded to e.g.o, so that's why it's there.

EDIT: To clarify, the delay is only applied to the callback for the workspace switching, not any of the other events

### CODE REVIEW

**Comment by zhanghai** [comment]
This is interesting, but sounds like something that should be fixed on GNOME Shell side. Have you reported a bug to their GitLab repository?

**Comment by stuarthayhurst** [comment]
I haven't filed an issue yet, as I wasn't entirely sure which project is technically at fault.

Since the information is requested mid-animation, I don't think it's actually *wrong*, and the window info could just be requested either side of the animation.

I'll send a report upstream, see what they have to say about it :)

**Comment by stuarthayhurst** [comment]
I did a bit more troubleshooting, it's got the correct workspace, and it's returning the list correctly, but it's incorrectly reporting that all windows are hidden, causing the top bar to be made invisible. Maybe this is being reported this way because it's mid animation and so the windows are actually hidden?

I'll ask in GNOME whether this is intended behaviour or not, and go from there.

**Comment by stuarthayhurst** [comment]
They suggested looking into the source code , and after tracing it back into the `MetaWindow` class in `mutter`, I think it's a race condition between mutter and the extension. The windows are being updated while we make the call to figure out if they're shown or not, do the delay gives the shell plenty of time to catch up.

**Comment by stuarthayhurst** [comment]
I'm happy to make changes to this PR if you'd rather something else, but I don't think this is really fixable upstream

**Comment by zhanghai** [comment]
Does 100ms always work, what if the user configured animations to run longer? (Please also take a look at my pending comment.)

In terms of monkey patching, will it be possible to patch `global.window_manager.completed_switch_workspace`? IMO simply patching `WindowManager._switchWorkspace()` directly may not work because we need to wait for the switch to complte, but that's in a callback function passed to `this._workspaceAnimation.animateSwitch()` within `WindowManager._switchWorkspace()`.

**Comment by stuarthayhurst** [comment]
Oh that's true, I hadn't investigated the monkey-patching that far.

I suppose we could use `imports.ui.windowManager.WINDOW_ANIMATION_TIME`, as that's the length of time an animation should take. The default is 250, so since we've got away with 100 so far, 250 should definitely be safe.

I won't be back for a short while, so if you're happy with that solution, feel free to commit the fix :)

**Comment by stuarthayhurst** [comment]
#40 should replace this, if it works for you too

**Pull request closed without merging**
